# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Fred Zhao
tagline:          Learn, Invent, Build, Learn
url:              http://fredzhao.com
paginate:         2
author:
  name:           Fred Zhao
  url:            https://twitter.com/frdzy

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/frdzy/fredzhao.com

# Posts
excerpt_separator: "<!-- more -->"
